### ISSUE TITLE
PrometheRule name is not compatble with kube-prometheus

### ISSUE THREAD

**Issue by rosskouk** [povilasv/coredns-mixin#21]
Hi,

I've added your coredns-mixin to kube-prometheus in the JSONNET file, it builds correctly but the PrometheusRule cannot be applied to the Kubernetes cluster as is contains upper case characters in the name.  When trying to apply the manifest the following error is raised:

```
The PrometheusRule "coreDNS" is invalid: metadata.name: Invalid value: "coreDNS": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Changing the start of the manifest as follows resolves the problem:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: coredns
  namespace: monitoring
```
